repos:
-   repo: local
    hooks:
    -   id: build-requirements
        name: Build requirements.txt
        entry: poetry export -o requirements.txt --without-hashes --without-urls
        files: poetry\.lock
        language: system
        pass_filenames: false
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: mixed-line-ending
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
    -   id: remove-crlf
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
    -   id: ruff
